# Showcase base configuration

# adapt those values to your needs
description:  Showcase - the portfolio and resume application
keywords:     resume, portfolio, projects

# languages you support
languages:  
    - en
    - de  

# change this if you have Google Analytics
google_analytics_code: UA-15774346-1

# usually you dont need to change those values
resumes_data:
    resumes.yml
projects_data:
    projects.yml
personal_data:
    me.yml